alphanumeric_all = {
    'A':['.- ','Morse_Code/Alpha/A_morse_code.ogg'], 
    'B':['-... ','Morse_Code/Alpha/B_morse_code.ogg'],
    'C':['-.-. ','Morse_Code/Alpha/C_morse_code.ogg'],
    'D':['-.. ','Morse_Code/Alpha/D_morse_code.ogg'],
    'E':['. ','Morse_Code/Alpha/E_morse_code.ogg'],
    'F':['..-. ','Morse_Code/Alpha/F_morse_code.ogg'],
    'G':['--. ','Morse_Code/Alpha/G_morse_code.ogg'],
    'H':['.... ','Morse_Code/Alpha/H_morse_code.ogg'],
    'I':['.. ','Morse_Code/Alpha/I_morse_code.ogg'] ,
    'J':['.--- ','Morse_Code/Alpha/J_morse_code.ogg'],
    'K':['-.- ','Morse_Code/Alpha/K_morse_code.ogg'],
    'L':['.-.. ','Morse_Code/Alpha/L_morse_code.ogg'],
    'M':['-- ','Morse_Code/Alpha/M_morse_code.ogg'],
    'N':['-. ','Morse_Code/Alpha/N_morse_code.ogg'],
    'O':['--- ','Morse_Code/Alpha/O_morse_code.ogg'],
    'P':['.--. ','Morse_Code/Alpha/P_morse_code.ogg'],
    'Q':['--.- ','Morse_Code/Alpha/Q_morse_code.ogg'],
    'R':['.-. ','Morse_Code/Alpha/R_morse_code.ogg'],
    'S':['... ','Morse_Code/Alpha/S_morse_code.ogg'],
    'T':['- ','Morse_Code/Alpha/T_morse_code.ogg'],
    'U':['..- ','Morse_Code/Alpha/U_morse_code.ogg'],
    'V':['...- ','Morse_Code/Alpha/V_morse_code.ogg'],
    'W':['.-- ','Morse_Code/Alpha/W_morse_code.ogg'],
    'X':['-..- ','Morse_Code/Alpha/X_morse_code.ogg'],
    'Y':['-.-- ','Morse_Code/Alpha/Y_morse_code.ogg'],
    'Z':['--.. ','Morse_Code/Alpha/Z_morse_code.ogg'],
    ' ':['  ',''],
    '1':['.---- ','Morse_Code/Numerics/1_number_morse_code.ogg'],
    '2':['..--- ','Morse_Code/Numerics/2_number_morse_code.ogg'],
    '3':['...-- ','Morse_Code/Numerics/3_number_morse_code.ogg'],
    '4':['....- ','Morse_Code/Numerics/4_number_morse_code.ogg'],
    '5':['..... ','Morse_Code/Numerics/5_number_morse_code.ogg'],
    '6':['-.... ','Morse_Code/Numerics/6_number_morse_code.ogg'],
    '7':['--... ','Morse_Code/Numerics/7_number_morse_code.ogg'],
    '8':['---.. ','Morse_Code/Numerics/8_number_morse_code.ogg'],
    '9':['----. ','Morse_Code/Numerics/9_number_morse_code.ogg'],
    '0':['----- ','Morse_Code/Numerics/0_number_morse_code.ogg'],
    '.':['.-.-.-','Morse_Code/Symbols/Morse_Code_-_Period.ogg'],
    ',':['--..--','Morse_Code/Symbols/Morse_Code_-_Comma.ogg'],
    '?':['..--..','Morse_Code/Symbols/Morse_Code_-_Question_Mark.ogg'],
    '\'':['.----.','Morse_Code/Symbols/Morse_Code_-_Apostrope.ogg'],
    '!':['-.-.--','Morse_Code/Symbols/Morse_Code_-_Exclamation_Point.ogg'],
    '/':['-..-.','Morse_Code/Symbols/Morse_Code_-_Slash.ogg'],
    '(':['-.--.','Morse_Code/Symbols/Morse_Code_-_Parenthesis_(Open).ogg'],
    ')':['-.--.-','Morse_Code/Symbols/Morse_Code_-_Parenthesis_(Close).ogg'],
    '&':['.-...','Morse_Code/Symbols/Morse_Code_-_Ampersand.ogg'],
    ':':['---...','Morse_Code/Symbols/Morse_Code_-_Colon.ogg'],
    ';':['-.-.-.','Morse_Code/Symbols/Morse_Code_-_Semicolon.ogg'],
    '=':['-...-','Morse_Code/Symbols/Morse_Code_-_Equals.ogg'],
    '+':['.-.-.','Morse_Code/Symbols/Morse_Code_-_Plus.ogg'],
    '-':['-....-','Morse_Code/Symbols/Morse_Code_-_Hyphen,_Minus.ogg'],
    '_':['..--.-','Morse_Code/Symbols/Morse_Code_-_Underscore.ogg'],
    '\"':['.-..-.','Morse_Code/Symbols/Morse_Code_-_Quotation_Mark.ogg'],
    '$':['...-..-','Morse_Code/Symbols/Morse_Code_-_Dollar_Sign.ogg'],
    '@':['.--.-.','Morse_Code/Symbols/Morse_Code_-_At_(Commercial_At).ogg']
}
